pipeline {
  agent any
  environment {
     GOOGLE_APPLICATION_CREDENTIALS = credentials('jkey')
  }
  stages {
     stage ("connecting to git") {
        steps{
          git branch : "main", url : "https://github.com/sgandeplli/instance-exits.git"
        }
    }

    stage ("terraform initlation"){
        steps{
          sh "terraform init"
          sh "terraform plan"
          sh "terraform apply -auto-approve"  
        }
    }
  }

}
